config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'

  get 'blogs/show'

  mount Ckeditor::Engine => '/ckeditor'
  resources :favorites, only: ['index']

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {confirmations: 'confirmations'}

  resources :properties do
    resources :images, only: [:new, :create]
    
    member do
      get 'mark_favorite'
    end

    collection do 
      get 'search'
    end

    collection do
      post :search, to: 'properties#index'
    end
    
    collection do 
      get 'neighbour_hood_locations'
    end
    
    collection do
      get 'tag_search'
    end
    
    collection do
      post 'contact_form'
    end
    
    collection do
      post 'newsletter'
    end
    
    collection do 
      get 'rent'
    end
    
    collection do 
      get 'buy'
    end

    member do
      get 'Unpublish'
    end
  end
  
  resources :blogs, only: [:index, :show]

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  HighVoltage.configure do |config|
  	config.route_drawer = HighVoltage::RouteDrawers::Root
  end

  HighVoltage.configure do |config|
  	config.home_page = 'index'	
  end  
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_attached_file :image, 
  styles: { medium: "300x300>", thumb: "100x100>" }, 
  default_url: ActionController::Base.helpers.asset_path("images/blog-img1.jpg")
  
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
  validates :title, presence: true
  validates :image, presence: true
  validates :description, length: { minimum: 15 }
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all.page(params[:page]).per(3)
  end

  def show
    @blog = Blog.find(params[:id])
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="blog-post shadow-hover">
  <a href="<%= blog_path(blog) %>" class="blog-post-img">
    <div class="img-fade"></div>
    <%= image_tag blog.image.url, style: 'width: 100%; height: 500px' %>
  </a>
  <div class="content blog-post-content">
    <h3><a href="<%= blog_path(blog) %>"> <%= blog.title %> </a></h3>
    <p> <%= blog.created_at.strftime("%d %b. %Y") %> </p>
    <p style="margin-top: -2%;"> By <strong> <%= blog.author %> </strong> </p>
    <p> <%= truncate(blog.description, length: 350) %> </p>
    <a href="<%= blog_path(blog) %>" class="button button-icon small alt"><i class="fa fa-angle-right"></i> Read More</a>
  </div>
</div>

app/views/blogs/index.html.erb
<section class="subheader" style="background-image: url(<%= Setting.first.blog_top_image.url %>);">
  <div class="container">
    <h1>Blogs</h1>
    <div class="breadcrumb right">Home <i class="fa fa-angle-right"></i> <a href="#" class="current">Blogs</a></div>
    <div class="clear"></div>
  </div>
</section>

<section class="module">
  <div class="container">
    
    <div class="row">
      <div class="col-lg-12">

        <%= render @blogs %>

      </div><!-- end blog posts -->
    </div><!-- end row -->
    
    <%= paginate @blogs, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-small pagination-centered" %>

  </div><!-- end container -->
</section>

<%= render 'newsletter' %>

app/views/blogs/show.html.erb
<section class="subheader" style="background-image: url(<%= Setting.first.blog_top_image.url %>);">
  <div class="container">
    <h1><%= @blog.title %></h1>
    <div class="breadcrumb right">Home <i class="fa fa-angle-right"></i> <a href="#">Blog</a> <i class="fa fa-angle-right"></i> <a href="#" class="current"><%= @blog.title %></a></div>
    <div class="clear"></div>
  </div>
</section>

<section class="module">
  <div class="container">
    
    <div class="row">
      <div class="col-lg-8 col-md-8">

        <div class="blog-post">
          <a href="#" class="blog-post-img">
            <div class="img-fade"></div>
            <%= image_tag @blog.image.url, style: 'width: 100%; height: 500px' %>
          </a>
          <div class="content blog-post-content">
            <h3><a href="#"><%= @blog.title %></a></h3>
            <p> <%= @blog.created_at.strftime("%d %b. %Y") %> </p>
            <p style="margin-top: -2%;"> By <strong> <%= @blog.author %> </strong> </p>
            <p><%= @blog.description %></p>
          </div>
        </div><!-- end blog post -->
      </div><!-- end blog posts -->
      <div class="col-lg-4 col-md-4 sidebar">
        <div class="widget widget-sidebar recent-properties">
          <h4><span>View More Properties</span> <%= image_tag "images/divider-half.png" %></h4>
          <div class="widget-content">
          <% @recents = Property.order(id: :desc).where(:isPublished => 1).first(4) %>
          <% @recents.each do |recent| %> 
          
          <div class="recent-property">
            <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4"><a href="<%= property_path(recent) %>"><%= image_tag recent.image.url %></a></div>
            <div class="col-lg-8 col-md-8 col-sm-8">
              <h5><a href="<%= property_path(recent) %>"><%= recent.title %></a></h5>
              <p><strong><%= recent.price %> SDG</strong> Per Month</p>
            </div>
            </div>
          </div>
           
           <% end %>  
          
          </div><!-- end widget content -->
        </div><!-- end widget -->
      </div>
    </div>

  </div>
</section>

<%= render 'newsletter' %>

<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-598b62ce6aeb1503"></script>