config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'

  get 'blogs/show'

  mount Ckeditor::Engine => '/ckeditor'
  resources :favorites, only: ['index']

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {confirmations: 'confirmations'}

  resources :properties do
    resources :images, only: [:new, :create]
    
    member do
      get 'mark_favorite'
    end

    collection do 
      get 'search'
    end

    collection do
      post :search, to: 'properties#index'
    end
    
    collection do 
      get 'neighbour_hood_locations'
    end
    
    collection do
      get 'tag_search'
    end
    
    collection do
      post 'contact_form'
    end
    
    collection do
      post 'newsletter'
    end
    
    collection do 
      get 'rent'
    end
    
    collection do 
      get 'buy'
    end

    member do
      get 'Unpublish'
    end
  end
  
  resources :blogs, only: [:index, :show]

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  HighVoltage.configure do |config|
  	config.route_drawer = HighVoltage::RouteDrawers::Root
  end

  HighVoltage.configure do |config|
  	config.home_page = 'index'	
  end  
end

app/models/property.rb
class Property < ApplicationRecord

	belongs_to :user
	has_many   :images
	accepts_nested_attributes_for :images, allow_destroy: true

	has_many   :favorites
	# has_many   :users, through: :favorites

	has_attached_file :image, styles: { large: "750x441>", medium: "600x600>", thumb: "100x100#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	geocoded_by :address
	after_validation :geocode, :if => :address_changed?

	scope :published, ->{ where(isPublished: 1) }
	scope :unpublished, ->{ where(isPublished: 0) }
	scope :featured, ->{ where(isFeatured: 1) }
	scope :not_featured, ->{ where(isFeatured: 0) }
	scope :rent, ->{ where(tag: "Rent") }
	scope :sell, ->{ where(tag: "Sell") }
	scope :Sold, ->{ where(status: "Sold") }
	scope :Rented, ->{ where(status: "Rented") }

	validates :title, presence: true
	validates :address, presence: true
	validates :listing_type, presence: true
	validates :location, presence: true
	validates :bedrooms, presence: true
	validates :bath, presence: true
	validates :tag, presence: true
	validates :area, presence: true
	validates :price, presence: true
	validates :availibility, presence: true
	validates :image, presence: true
	validates :address, length: { minimum: 10 }
	validates :description, length: { minimum: 15 }
	validates :currency, presence: true
	validates :description, presence: true
	validates :user, presence: true
	validates :unit, presence: true
	validate :empty_land_option_for_sell_tag

	def empty_land_option_for_sell_tag
		if self.listing_type == "Empty Land" && self.tag != "Sell"
			errors.add(:tag, "can't be rent for Empty Land type property. ")
		end
	end

	def to_param
		"#{id} #{title}".parameterize
	end

	def self.search(search)
		if(search)
			where(["title LIKE ? AND isPublished = ?","%#{search}%", "1"])
		else
			order(:id => :DESC).where(isPublished: 1)
		end	
	end

	def price_with_currency
		price.to_s + ' ' + currency
	end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    if params[:q].present? && @search.result
      @search_properties = @search.result
      @properties = @search_properties.where(isPublished: 1)
      @count = @properties.count
      @properties = Kaminari.paginate_array(@properties).page(params[:page]).per(5)
    else
      @properties = Property.where(:isPublished => 1).all
      @count = @properties.count
      @properties = Kaminari.paginate_array(@properties).page(params[:page]).per(5)
    end  
  end

  def mark_favorite
    @favorite  = Favorite.new(:property_id => params[:id])
    @favorite.user_id = current_user.id
    if @favorite.save
      redirect_to property_path(@favorite.property_id), :notice => "You have marked this property as Favorite. "
    else
      redirect_to property_path(@favorite.property_id), :notice => "Your Property is not Marked as Favorite. "
    end 
  end

  def search
    @search_properties = @search.result
    @properties = @search_properties.where(:isPublished => 1)
    @count = @properties.count
    @properties = Kaminari.paginate_array(@properties).page(params[:page]).per(5)
    
    render 'index'
  end
  
  def tag_search
    @search_properties = @search.result
    @properties = @search_properties.where(:isPublished => 1)
    @count = @properties.count
    @properties = Kaminari.paginate_array(@properties).page(params[:page]).per(5)
    
    render "index"
  end
  
  def neighbour_hood_locations
    @properties = Property.near(params[:neighbourhoods], 2)
    @count = @properties.count
    @properties = Kaminari.paginate_array(@properties).page(params[:page]).per(5)
    
    render "index"
  end

  def new
  	if user_signed_in?
  		@property = Property.new
  	else
  		redirect_to page_path('index'), :notice => "You must be Logged in to Submit Property "
  	end		
  end

  def create
  	@user = current_user
  	@property =  @user.properties.build(property_params)
  	if @property.save
  		redirect_to property_path(@property), :notice => "Your Property has been Saved. "
  	else
  		render :new
  	end 
  end	

  def edit
  	@property = Property.find(params[:id])
  	authorize! :update, @property 
  end

  def update
  	@property = Property.find(params[:id])
  	authorize! :update, @property

    if @property.update_attributes(property_params)
  	  redirect_to property_path, :notice => "Your Property has been Updated. "
    else 
  	  render "edit"
  	end
  end	

  def show
    @search = Property.ransack(params[:q])  
  	@property = Property.find(params[:id])
    @locations = Property.distinct.pluck(:location)
    @image = Image.new
  end

  def destroy
  	@property = Property.find(params[:id])
  	authorize! :destroy, @property
  	@property.destroy
  	redirect_to properties_path, :notice => "Your Property has been Deleted. "
  end	
  
  def contact_form
    @name = params[:name]
    @email = params[:email]
    @phone = params[:phone]
    @subject = params[:subject]
    @message = params[:message]
    
    if ContactMailer.contact(@name, @email, @phone, @subject, @message).deliver
      redirect_to page_path('contact'), notice: 'Thank you for contacting us.'
    else
      redirect_to page_path('contact'), notice: 'Some problem Occured, try again later.'
    end
  end
  
  def newsletter
    @email = params[:email]
    @newsletter = Newsletter.create(email: @email)
    
    respond_to do |format|
      if @newsletter.save
       format.html { redirect_to page_path('index'), notice: 'Thank you for Subscribing.' }
       format.js
      else
       format.html { redirect_to page_path('index'), notice: 'Some problem Occured, try again later.' }
       format.js
      end
    end
  end
  
  def rent
    @properties = Property.where(isPublished: 1)
    @properties = @properties.where(tag: 'Rent')
    @count = @properties.count
    @properties = Kaminari.paginate_array(@properties).page(params[:page]).per(5)
    
    render 'index'
  end
  
  def buy
    @properties = Property.where(isPublished: 1)
    @properties = @properties.where(tag: 'Sell')
    @count = @properties.count
    @properties = Kaminari.paginate_array(@properties).page(params[:page]).per(5)
    
    render 'index'
  end

  def Unpublish
    @property = Property.find(params[:id])
    @property.update(isPublished: 0)
    @property.update(unpublished_date: DateTime.now)
    @property.save
    redirect_to page_path('my_properties'), notice: 'Propertiy is successfully Unpublished'
  end

  def property_params
	 params.require(:property).permit!
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_advanced_search.html.erb
<div class="col-lg-4 col-md-4 sidebar">
		
<div class="widget widget-sidebar sidebar-properties advanced-search" style="margin-top: auto;">
  <h4><span>Advanced Search</span> <%= image_tag "images/divider-half.png" %> </h4>
  <div class="widget-content box">
  	<%= search_form_for @search, url: search_properties_path, method: :post do |f| %>

	  <div class="form-block border">	
	  	<%= f.label :title_cont, "Title" %>
	  	<%= f.text_field :title_cont, placeholder: "Any", class: "border" %>	
	  </div>

	  <div class="form-block border">
			<%= f.label :location_eq, "Location" %>
			<%= f.select :location_eq, options_for_select([["Khartoum", "Khartoum"], ["Bahri/Khartoum North", "Bahri/Khartoum North"], ["Omdurman", "Omdurman"]]), {include_blank: "Select Location" }, { class: "border" }%>
	  </div>

	  <div class="form-block border">
			<%= f.label :tag_cont, "Property Tag" %>
			<%= f.select :tag_cont, options_for_select([["Rent", "Rent"], ["Buy", "Sell"]]), { include_blank: "Select Tag" }, { class: "border" }%>
	  </div>

	  <div class="form-block border">
			<%= f.label :listing_type_eq, "Property Listing Type" %>
			<%= f.select :listing_type_eq, options_for_select([["Apartment", "Apartment"], ["House", "House"], ["Villa", "Villa"], ["Office", "Office"], ["Farm", "Farm"], ["Empty Land", "Empty Land"]]), { include_blank: "Select Listing Type" }, { class: "border" } %>
	  </div>

	  <div class="form-block">
			<label>Bedrooms</label>
			<%= f.number_field :bedrooms_gteq, class: "area-filter border", placeholder: "Min Bedrooms", min: 0 %>
			<%= f.number_field :bedrooms_lteq, class: "area-filter border", placeholder: "Max Bedrooms", min: 0 %>
			<div class="clear"></div>
	  </div>

	  <div class="form-block">
			<label>Bathrooms</label>
			<%= f.number_field :bath_gteq, class: "area-filter border", placeholder: "Min Bathrooms", min: 0 %>
			<%= f.number_field :bath_lteq, class: "area-filter border", placeholder: "Max Bathrooms", min: 0 %>
			<div class="clear"></div>
	  </div>

	  <div class="form-block border">
	  	<label>Area Unit</label>
      <%= f.select :unit_eq, options_for_select([["Acre", "Acre"], ["Square Meter", "Square Meter"]]), { include_blank: "Select Area Unit" }, { class: 'border' } %>
      <div class="clear"></div>
    </div>

	  <div class="form-block">
			<label>Area</label>
			<%= f.number_field :area_gteq, class: "area-filter border", placeholder: "Select Min Area", min: 0 %>
			<%= f.number_field :area_lteq, class: "area-filter border", placeholder: "Select Max Area", min: 0 %>
			<div class="clear"></div>
	  </div> 

	  <div class="form-block">
			<input type="submit" class="button" value="Find Properties" />
	  </div>

	<% end %>
  </div><!-- end widget content -->
</div><!-- end widget -->

app/views/properties/_properties.html.erb
<% @properties.each do |property| %>
			
	<div class="property property-row property-row-sidebar shadow-hover">
      <a href="<%= property_path(property) %>" class="property-img">
        <div class="img-fade"></div>
        <% if property.tag == 'Sell' %>
          <div class="property-tag button status responsive-property-tag">For Sale </div>
        <% else %>
          <div class="property-tag button status responsive-property-tag">For <%= property.tag %> </div>
        <% end %>
        <div class="property-price responsive-property-price"> <%= number_with_delimiter(property.price, delimiter: ',') %> <%= property.currency %> </div>
        <div class="property-color-bar"></div>
        <%= image_tag property.image.url, style: "width: 100%; height: 245px;" %>
      </a>
      <div class="property-content">
        <div class="property-title responsive-property-content">
          <h4><a href="#"><%= link_to property.title, property_path(property) %></a></h4>
          <p class="property-address"><i class="fa fa-map-marker icon"></i><%= property.address %></p>
          <div class="clear"></div>
          <p class="property-text"><%= truncate(property.description, length: 30) %></p>
        </div>
        <table class="property-details responsive-property-details">
          <tr>
            <td><i class="fa fa-bed"></i> <%= property.bedrooms %> Bedrooms </td>
            <td><i class="fa fa-tint"></i> <%= property.bath %> Bathrooms </td>
            <td><i class="fa fa-expand"></i> <%= property.area %> <%= property.unit %> </td>
          </tr>
        </table>
      </div>
      <div class="property-footer responsive-property-footer">
        <span class="left"><i class="fa fa-calendar-o icon"></i> <%= time_ago_in_words(property.created_at) %> ago</span>
        <span class="right">
          <% if user_signed_in? %>
            <% u = User.find(current_user.id) %>
            <% if u.favorites.find_by_property_id(property.id).blank? %>
              <%= link_to "",mark_favorite_property_path(property), :class => "fa fa-heart-o icon" %>
            <% else %>  
              <%= link_to "",'#', :class => "fa fa-heart icon" %>
            <% end %>
          <% end %>    
          <a href="<%= property_path(property) %>" class="button button-icon" style="margin-top: 0%;"><i class="fa fa-angle-right"></i>Details</a>
        </span>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
  </div>

<% end %>

<span><%= paginate @properties, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-small pagination-centered" %></span>

app/views/properties/edit.html.erb
<section class="subheader">
  <div class="container">
    <h1>Edit Property</h1>
    <div class="breadcrumb right">Home <i class="fa fa-angle-right"></i> <a href="#" class="current">Edit Property</a></div>
    <div class="clear"></div>
  </div>
</section>

<section class="module property-submit">
  <div class="container">

    <div class="row">
    <div class="col-lg-10 col-lg-offset-1">

    <!-- <form class="multi-page-form" method="post"> -->
   
	<%= render "form" %>
        
    <div class="clear"></div>

    </div><!-- end basic info -->

  </div><!-- end col -->
  </div><!-- end row -->

  </div><!-- end container -->
</section>

<%= render 'newsletter' %>

app/views/properties/new.html.erb
<section class="subheader">
  <div class="container">
    <h1>Submit Property</h1>
    <div class="breadcrumb right">Home <i class="fa fa-angle-right"></i> <a href="#" class="current">Submit Property</a></div>
    <div class="clear"></div>
  </div>
</section>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content" style="background-color: #0f8845;color: white;">
      <div class="modal-header" style="background-color: #0f8845;color: white;">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" style="background-color: #0f8845;color: white;">To Get your Property Live</h4>
      </div>
      <div class="modal-body">
        <p>To make sure your property gets live on our website, You need to contact us. We will save it in our database but it's still Unpublished.</p>
      </div>
      <div class="modal-footer" style="background-color: #0f8845;color: white;">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
<!-- Modal End-->

<section class="module property-submit">
  <div class="container">

    <div class="row">
    <div class="col-lg-10 col-lg-offset-1">

    <!-- <form class="multi-page-form" method="post"> -->
   
	<%= render "form" %>
        
    <div class="clear"></div>

    </div><!-- end basic info -->

  </div><!-- end col -->
  </div><!-- end row -->

  </div><!-- end container -->
</section>

<%= render 'newsletter' %>

app/views/properties/newsletter.js.erb
$('#newsletter_p').hide().fadeIn(300, function(){
  $(this).html('Thank you for subscribing to our newsletter.')
})

app/views/properties/show.html.erb
<% WtfLang::API.key = "fa9d6d9faf06420ada0090796f8c778d" %>

<section class="subheader">
  <div class="container">
    <h1><%= @property.title %></h1>
    <div class="breadcrumb right"> <%= link_to "Home", page_path('index') %> <i class="fa fa-angle-right"></i> <%= link_to "Properties", properties_path %> <i class="fa fa-angle-right"></i> <a href="#" class="current"><%= @property.title %></a></div>
    <div class="clear"></div>
  </div>
</section> 	

<% flash.each do |key,value| %>
	<div class="alert-box success" style="width: 35%; margin-left: 8%; margin-top: 2%; margin-bottom: -3%; ">
		<span style="float: left"><i class="fa fa-check icon"></i></span>
		<p id="notice" style="margin-bottom: 0%;"><%= value %></p>
	</div>
<% end %>

<section class="module">
  <div class="container">
  
	<div class="row">
		<div class="col-lg-8 col-md-8">

			<% if @property.isPublished != 1 %>
				<!-- ImageAdd Form -->
				<div class="widget property-single-item property-agent" style="background-color: antiquewhite;">
					<h4>
						<span>Important Notice</span> <%= image_tag "images/divider-half.png", :class => "divider-hex" %>
						<div class="divider-fade"></div>
					</h4>
					<div>
						<p style="font-size: medium; font-family: sans-serif;">Before Your Property is published, You must first contact us. Your property will go live as soon as we can verify all information. Thank you!</p>  
				        <div class="clear"></div>
				    </div>
				</div>
				<!-- End ImageAdd Form -->
			<% end %>	
		
			<div class="property-single-item property-main">
				<div class="property-header">
					<div class="property-title">
						<h4><%= @property.title %></h4>
            <div class="property-price-single right"><%= number_with_delimiter(@property.price, delimiter: ',') %> <%= @property.currency %> <span><%= "Per Month" if @property.tag == "Rent" %></span></div>
						<p class="property-address"><i class="fa fa-map-marker icon"></i><%= @property.address %></p>
            <div class="clear"></div>
					</div>
					<div class="property-single-tags">
						<div class="property-tag button status" style="background: blueviolet">
							<% if @property.tag == 'Sell' %>
			          For Sale
			        <% else %>
			          For <%= @property.tag %>
			        <% end %>
						</div>
						
						<% if !@property.status.present? && @property.tag == 'Sell' %>
							<div class="property-tag button status" style="background: yellow">
								<strong style="color: black;">Not Sold Yet</strong>
							</div>
						<% elsif @property.status.present? && @property.tag == 'Sell' %>
							<div class="property-tag button status" style="background: crimson">
								<strong>Property Sold</strong>
							</div>
						<% elsif !@property.status.present? && @property.tag == 'Rent' %>
							<div class="property-tag button status" style="background: yellow">
								<strong style="color: black;">Not Rented Yet</strong>
							</div>
						<% else %>
							<div class="property-tag button status" style="background: crimson">
								<strong>Property Rented</strong>
							</div>
						<% end %>
						
						<% if can? :update, @property %>
						 	<div class="property-tag button alt featured"><%= link_to "Edit", 	edit_property_path(@property), style: "color: white;" %></div>
						 <% end %>

						 <% if can? :destroy, @property %>
						 	<div class="property-tag button alt2 featured"><%= link_to "Delete", property_path(@property), style: "color: white;", method: :delete, data: {confirm: "You sure?"} %></div>
						 <% end %>	

						<div class="property-type right">
							<div class="row">
								<div class="col-lg-6 col-md-6 col-sm-6 listing_type">
									Property Type: <a href="#"><%= @property.listing_type %></a>
								</div>
								<div class="col-lg-6 col-md-6 col-sm-6 requisition_number">
									Requisition Number: <a href="#"><%= @property.id %></a>
								</div>
							</div>
						</div>
					</div>
				</div>

				<table class="property-details-single">
					<tr>
						<td><i class="fa fa-bed"></i> <span><%= @property.bedrooms %></span> Bedrooms</td>
						<td><i class="fa fa-tint"></i> <span><%= @property. bath %></span> Bathrooms</td>
						<td><i class="fa fa-expand"></i> <span><%= @property.area %></span> <%= @property.unit %> </td>
					</tr>
				</table>

        <div class="property-gallery">
         
          <div class="slider-nav slider-nav-property-gallery">
            <span class="slider-prev"><i class="fa fa-angle-left"></i></span>
            <span class="slider-next"><i class="fa fa-angle-right"></i></span>
          </div>
          
          <div class="slide-counter"></div>
          
          <div class="slider slider-property-gallery">
            <div class="slide"><%= image_tag @property.image.url(:large), style: "width: 750px;position: relative;left: 0px;top: 0px;z-index: 999;opacity: 1;height: 492px" %></div>
            <% @property.images.each do |img| %>
            	
            	<div class="slide">
            		<%= image_tag img.image.url, style: "width: 750px;position: relative;left: 0px;top: 0px;z-index: 999;opacity: 1;height: 492px" %>
            	</div>

			<% end %>
          </div>
          
          <div class="slider property-gallery-pager">
          	<a class="property-gallery-thumb" style="height: 83px;"><%= image_tag @property.image.url %></a>
          	<% @property.images.each do |img| %>
            	<a class="property-gallery-thumb" style="height: 83px;"><%= image_tag img.image.url %></a>
			<% end %>

          </div>

        </div>

			</div><!-- end property title and gallery -->

			<% if can? :create, @property.images.build %>
				<!-- ImageAdd Form -->
				<div class="widget property-single-item property-agent">
					<h4>
						<span>Add Images</span> <%= image_tag "images/divider-half.png", :class => "divider-hex" %>
						<div class="divider-fade"></div>
					</h4>
					<div>
						<%= render "images/form" %>  
			        <div class="clear"></div>
				    </div>
				</div>
				<!-- End ImageAdd Form -->
			<% end %>	
			<div class="widget property-single-item property-description content">
				<h4>
					<span>Description</span> <%= image_tag "images/divider-half.png", :class => "divider-hex" %>
				</h4>
				
				<p <%= "dir=rtl" if @property.description.full_lang == 'arabic' %>>
					<%= raw(@property.description) %>
				</p>

				<div>
					<a href="#"><i class="fa fa-pencil icon"></i>Additional Details</a> <hr>
	        <div id="tabs-1" class="">
	          <ul>
	          	<div class="row">
		          	<div class="col-lg-6 col-md-6">
			          	<li class="details">Property Location: <span><%= @property.location %></span></li>
			          	<li  class="details">Property Availability: <span><%= @property.availibility %></span></li>
			          	<li class="details">Furnished: <span><%= human_boolean(@property.furnished) %></span></li>
			          </div>
		          	<div class="col-lg-6 col-md-6">
			          	<li  class="details">Posted at: <span><%= time_ago_in_words(@property.created_at) %> ago</span></li>
			          	<li class="details">Longitude: <span><%= @property.longitude %></span></li>
			          	<li class="details">Latitude: <span><%= @property.latitude %></span></li>
		          	</div>
		          </div>
	          </ul>
	        </div>
	    	</div>
			</div><!-- end description -->

			<div class="widget property-single-item property-location">
				<h4>
					<span>Location</span> <%= image_tag "images/divider-half.png", :class => "divider-hex" %>
				</h4>
				<div id="map-single"><p align="center">
				<% addr = @property.address.split(" ") %>
			<iframe
			  width="360"
			  height="300"
			  frameborder="0" style="border:0; margin-top: 0%;width: 100%; "
			  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCpelVemmv6M9GjBnXwltZaDs7VN66ybwY
			    &q=<%=addr.join('+')%>" allowfullscreen>
			</iframe>
		</p></div>
			</div><!-- end location -->

			<% if @property.tag != "Sell" %>
				<div class="widget property-single-item property-agent">
					<h4>
						<span>Agent Information</span> <%= image_tag "images/divider-half.png", :class => "divider-hex" %>
						<div class="divider-fade"></div>
					</h4>
					<div class="agent">
				        <a href="#" class="agent-img">
				            <div class="img-fade"></div>
				            <div class="button alt agent-tag"><%= @property.user.properties.count %> Properties</div>
				            <%= image_tag @property.user.image.url, alt: "" %>
				        </a>
				        <div class="agent-content">
				            <div class="agent-details" style="line-height: 2.5em">
				                <h4><a href="#"><%= @property.user.to_s.capitalize %></a></h4>
				                <p><i class="fa fa-envelope icon"></i><%= @property.user.email %></p>
				                <p><i class="fa fa-phone icon"></i><%= @property.user.contact %></p>
				                <% if @property.user.whats_app.present? %>
				                	<p> <i class="fa fa-whatsapp icon" style="font-size: 15px"></i> <%= @property.user.whats_app %> </p>
				                <% end %>
				            </div>
				        </div>
				        <div class="clear"></div>
				    </div>
				</div>
			<% else %>
				<div class="widget property-single-item property-agent">
					<h4>
						<span>Agent Information</span> <%= image_tag "images/divider-half.png", :class => "divider-hex" %>
						<div class="divider-fade"></div>
					</h4>
					<div class="agent">
						<div class="row">
							<div class="col-lg-1 col-md-1"></div>
							<div class="col-lg-4 col-md-4 responsive-agent-photo">
				        <a href="#" class="agent-img">
				            <div class=""></div>
				            <%= image_tag "images/logo4.png" %>
				        </a>
				      </div>
				      <div class="col-lg-4 col-md-4 sell-property-agent" style="margin-left: -20%; width: 38%;">
				        <div class="agent-content">
				            <div class="agent-details">
			                <h4><a href="#">Araddi Agent</a></h4>
			                <p><i class="fa fa-envelope icon"></i><%= Setting.first.email %></p>
			                <p style="width: 102%;"><i class="fa fa-phone icon"></i> <%= raw(Setting.first.phone) %> </p>
			                <p style="width: 105%;"><i class="fa fa-whatsapp icon" style="font-size: 15px"></i> <%= raw(Setting.first.whats_app) %> </p>
				            </div>
				            <ul class="social-icons">
			                <li>
			                	<a target="_blank" href="https://www.facebook.com/araddirealestate/">
			                		<i class="fa fa-facebook"></i>
			                	</a>
			                </li>
			                <li>
			                	<a target="_blank" href="https://www.instagram.com/araddi_com/?hl=en">
			                		<i class="fa fa-instagram"></i>
			                	</a>
			                </li>
			                <li>
			                	<a target="_blank" href="https://twitter.com/AraddiRealty">
			                		<i class="fa fa-twitter"></i>
			                	</a>
			                </li>
			                <li><a href="#"><i class="fa fa-youtube"></i></a></li>
				            </ul>
				        </div>
				      </div>
				      <div class="col-lg-3 col-md-3 sell-property-agent-contact">
				      	<a href="<%= page_path('contact') %>" class="button button-icon small right"><i class="fa fa-angle-right"></i>Contact US</a>
				      </div>
				      <div class="clear"></div>
				    </div>
				  </div>
				</div>
			<% end %>
			
		</div><!-- end col -->
		
			<%= render "advanced_search" %>

			<div class="widget widget-sidebar recent-properties">
			  <h4><span>View More Properties</span> <%= image_tag "images/divider-half.png" %></h4>
			  <div class="widget-content">
			  <% @recents = Property.order(id: :desc).where(:isPublished => 1).first(3) %>
			  <% @recents.each do |recent| %>	
				
				<div class="recent-property">
				  <div class="row">
					<div class="col-lg-4 col-md-4 col-sm-4"><a href="<%= property_path(recent) %>"><%= image_tag recent.image.url %></a></div>
					<div class="col-lg-8 col-md-8 col-sm-8">
					  <h5><a href="<%= property_path(recent) %>"><%= recent.title %></a></h5>
					  <p><strong><%= recent.price %> <%= recent.currency %> </strong> Per Month </p>
					</div>
				  </div>
				</div>
			   
			   <% end %>	
				
			  </div><!-- end widget content -->
			</div><!-- end widget -->
		
		</div><!-- end sidebar -->
		
	</div><!-- end row -->

  </div><!-- end container -->
</section>

<%= render 'newsletter' %>

<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-598b62ce6aeb1503"></script>