config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'

  get 'blogs/show'

  mount Ckeditor::Engine => '/ckeditor'
  resources :favorites, only: ['index']

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {confirmations: 'confirmations'}

  resources :properties do
    resources :images, only: [:new, :create]
    
    member do
      get 'mark_favorite'
    end

    collection do 
      get 'search'
    end

    collection do
      post :search, to: 'properties#index'
    end
    
    collection do 
      get 'neighbour_hood_locations'
    end
    
    collection do
      get 'tag_search'
    end
    
    collection do
      post 'contact_form'
    end
    
    collection do
      post 'newsletter'
    end
    
    collection do 
      get 'rent'
    end
    
    collection do 
      get 'buy'
    end

    member do
      get 'Unpublish'
    end
  end
  
  resources :blogs, only: [:index, :show]

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  HighVoltage.configure do |config|
  	config.route_drawer = HighVoltage::RouteDrawers::Root
  end

  HighVoltage.configure do |config|
  	config.home_page = 'index'	
  end  
end

app/views/pages/about.html.erb
<section class="subheader" style="background-image: url(<%= Setting.first.our_story_top_image.url %>);">
  <div class="container">
    <h1>Our Story</h1>
    <div class="breadcrumb right">Home <i class="fa fa-angle-right"></i> <a href="#" class="current">Our Story</a></div>
    <div class="clear"></div>
  </div>
</section>

<section class="module content">
  <div class="container">

    <div class="row">
      <div class="col-lg-12 col-md-12">
        <p style="text-align: center; margin-bottom: -0.5%;"> <%= image_tag "images/divider.png", alt: "", style: 'margin-bottom: 2%;' %> </p>
        <p style="text-align: center;"> <%= raw(Setting.first.about_us_welcome_msg) %> </p>
        <p style="font-size: 17px; margin-left: 3%;"> <%= raw(Setting.first.about_us_text) %> </p>
      </div>
    </div> 

  </div>
</section>

<section class="module cta hexs" style="background: white">
  <div class="container">

    <div class="module-header">
      <h2 style="color: #566573">Explore the <strong>Marketplace</strong></h2>
      <%= image_tag "images/divider-white.png", alt: "" %>
    </div>

    <div class="row">
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="hex">
          <p><span style="margin-top: 5.5%;"><%= link_to 'Rent', rent_properties_path, style: 'color: white; font-style: bold' %></span></p>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="hex">
          <p><span style="margin-top: 5.5%;"><%= link_to 'Sell', page_path('sell'), style: 'color: white' %></span></p>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="hex">
          <p><span style="margin-top: 5.5%;"><%= link_to 'Buy', buy_properties_path, style: 'color: white' %></span></p>
        </div>
      </div>
    </div><!-- end row -->

  </div>
</section>

<section class="module cta image-bg" style="background-image: url(<%= Setting.first.our_story_background_image.url %>);">
  <div class="img-overlay blacker"></div>
  <div class="container">
    <h2>Learn more about the Sudan <strong>Real Estate</strong>.</h2>
    <a href="<%= blogs_path %>" class="button button-icon alt large"><i class="fa fa-angle-right"></i> Blog </a>
  </div><!-- end container -->
</section>

<%= render 'newsletter' %>

app/views/pages/contact.html.erb
<section class="subheader" style="background-image: url(<%= Setting.first.contact_us_top_image.url %>);">
  <div class="container">
    <h1>Contact Us</h1>
    <div class="breadcrumb right">Home <i class="fa fa-angle-right"></i> <a href="#" class="current">Contact Us</a></div>
    <div class="clear"></div>
  </div>
</section>

<section class="module contact-details">
  <div class="container">

    <div class="row">
      <div class="col-lg-3 col-md-3">
        <div class="contact-item">
          <i class="fa fa-envelope"></i>
          <h4>Email Us</h4>
          <p> <%= raw(Setting.first.email) %> </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-3">
        <div class="contact-item">
          <i class="fa fa-phone"></i>
          <h4>Call Us</h4>
          <a href="#"><p style="color: white"> <%= raw(Setting.first.phone) %> </p></a>
        </div>
      </div>
      <div class="col-lg-3 col-md-3">
        <div class="contact-item">
          <i class="fa fa-whatsapp"></i>
          <h4>Chat with Us</h4>
          <a href="#"> <p style="color: white"> <%= raw(Setting.first.whats_app) %> </p> </a>
        </div>
      </div>
      <div class="col-lg-3 col-md-3">
        <div class="contact-item">
          <i class="fa fa-share-alt"></i>
          <h4>Connect With Us</h4>
          <ul class="social-icons">
            <li>
              <a target="_blank" href="<%= raw(Setting.first.fb_link) %>">
                <i class="fa fa-facebook"></i>
              </a>
            </li>
            <li>
              <a target="_blank" href="<%= raw(Setting.first.instagram_link) %>">
                <i class="fa fa-instagram"></i>
              </a>
            </li>
            <li>
              <a target="_blank" href="<%= raw(Setting.first.twitter_link) %>">
                <i class="fa fa-twitter"></i>
              </a>
            </li>
            <li>
              <a target="_blank" href="<%= raw(Setting.first.youtube_link) %>">
                <i class="fa fa-youtube"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div><!-- end row -->

  </div>
</section>

<% flash.each do |key,value| %>
  <div class="alert-box success" style="width: 35%; margin-left: 8%; margin-top: 2%; margin-bottom: -3%; ">
    <span style="float: left"><i class="fa fa-check icon"></i></span>
    <p id="notice" style="margin-bottom: 0%;"><%= value %></p>
  </div>
<% end %>

<section class="module">
  <div class="container">

    <div class="row">

      <div class="col-lg-8 col-md-8">

        <div class="comment-form">
          <h4><span>Quick Contact</span> <%= image_tag "images/divider-half.png", alt: "" %></h4>
          <p> 
            <b> Tell us how we can improve our site? </b> 
            We’re always working to improve our user’s experience and we value your feedback. Let us know what we can do better.
          </p>
          
		  <form action="<%= contact_form_properties_path %>" method="post">
        <input name="utf8" type="hidden" value="✓">
        <input type="hidden" name="authenticity_token" value="wvP/4RGCvXYxBJ+pfqTeRzTI5pUdtRFuuP9eA5fNOmoawgH0jzsQgni4fUe9nTUmGjlsGl7GsEM82XxexhZSOA==">
        <div class="form-block">
          <label>Name *</label>
          <input class="requiredField" type="text" placeholder="Your Name" name="name" value="" required="" />
        </div>
        <div class="row">
          <div class="col-lg-6 col-md-6">
            <div class="form-block">
              <label>Email *</label>
              <input class="email requiredField" type="email" placeholder="Your email" name="email" value="" required="" />
            </div>
          </div>
          <div class="col-lg-6 col-md-6">
            <div class="form-block">
              <label>Phone</label>
              <input type="text" placeholder="Your phone" name="phone" value="" />
            </div>
          </div>
        </div>
        <div class="form-block">
              <label>Subject</label>
              <input type="text" placeholder="Subject" name="subject" value="" />
            </div>
        <div class="form-block">
          <label>Message *</label>
          <textarea class="requiredField" placeholder="Your message..." name="message" required=""></textarea>
        </div>
        <div class="form-block">
          <input type="submit" value="Submit" />
	        <input type="hidden" name="submitted" id="submitted" value="true" />
        </div>
      </form>
    </div>

        <div class="divider"></div><br/>
        <h4>Still need help?</h4>
        <p> <b> Do you have any questions? </b> Visit our <%= link_to 'FAQs', page_path('faq') %> page to find quick answers to your questions. </p>

      </div>
    </div><!-- end row -->

  </div><!-- end container -->
</section>

<%= render 'newsletter' %>

app/views/pages/faq.html.erb
<% @questions = Question.includes(:answer).all %>

<section class="subheader">
  <div class="container">
    <h1>Frequently Asked Questions</h1>
    <div class="breadcrumb right">Home <i class="fa fa-angle-right"></i> <a href="#" class="current">FAQ</a></div>
    <div class="clear"></div>
  </div>
</section>

<section class="module">
  <div class="container">

    <div class="row">
      <div class="col-lg-8 col-md-8">
        <div id="accordion" class="content">
          <% @questions.each do |question| %>
            <h3> <%= (question.question) %> </h3>
            <div> <%= raw(question.answer.answer) %> </div>
          <% end %>
        </div>
      </div>
      <div class="col-lg-4 col-md-4">

        <div class="widget widget-sidebar recent-properties">
        <h4><span>Recent Properties</span> <%= image_tag "images/divider-half.png" %></h4>
        <div class="widget-content">
        <% @recents = Property.order(id: :desc).where(:isPublished => 1).first(3) %>
        <% @recents.each do |recent| %> 
        
        <div class="recent-property">
          <div class="row">
          <div class="col-lg-4 col-md-4 col-sm-4"><a href="<%= property_path(recent) %>"><%= image_tag recent.image.url %></a></div>
          <div class="col-lg-8 col-md-8 col-sm-8">
            <h5><a href="<%= property_path(recent) %>"><%= recent.title %></a></h5>
            <p><strong>$<%= recent.price %></strong> Per Month</p>
          </div>
          </div>
        </div>
         
         <% end %>  
        
        </div><!-- end widget content -->
      </div><!-- end widget -->
        
      </div>
    </div><!-- end row -->

  </div>
</section>

<%= render 'newsletter' %>

app/views/pages/feedback.html.erb
<section class="subheader">
  <div class="container">
    <h1 style="color: #EBEDEF">Website Feedback</h1>
    <div class="breadcrumb right">Home <i class="fa fa-angle-right"></i> <a href="#" class="current">Website Feedback</a></div>
    <div class="clear"></div>
  </div>
</section>

<section class="module content" style="background: white">
  <div class="container">

    <div class="row">
      <div class="col-lg-12 col-md-12" style="text-align: center">
        <%= image_tag "images/divider.png", alt: "" %>
        <p><strong style="color: #566573 !important"> <h3> How can we improve our site? </h3> </strong> </p>
        <p style="color: #566573 !important; font-size: 17px">
          We’re always working to improve our user experience and we value your feedback. Let us know what we can do better.
        </p>
        <%= link_to 'Contact Us', page_path('contact'), style: 'background: #48a0dc; color: white; padding: 10px; border-radius: 4px; padding-left: 30px; padding-right: 30px' %>
      </div>
    </div> 

  </div>
</section>

<%= render 'newsletter' %>

app/views/pages/index.html.erb
<section class="subheader simple-search" style="background-image: url(<%= Setting.first.main_image.url %>);">
  <div class="container">
    <% flash.each do |key,value| %>
      <div class="alert-box success" style="width: 42%; margin-left: 29%; margin-top: -2%; margin-bottom: 5%; background-color: transparent;">
        <span style="float: left; margin-top: 1%;"><i class="fa fa-check icon"></i></span>
        <p id="notice" style="margin-bottom: 0%; margin-top: auto;"><%= value %></p>
      </div>
    <% end %>
    <h2 class="main-heading" style="margin-left: -23%; color: white; margin-top: -3%;"> A Simple Way to Find Real Estate in Khartoum </h2>
    <div class="tabs" style="margin-left: -65%; margin-top: 2%;">
      <ul style="margin-left: -7%;" class="tabs_ul">
        <li><a href="#tabs-1">Rent</a></li>
        <li><a href="#tabs-3">Buy</a></li>
      </ul>
      
      <div id="tabs-1" class="ui-tabs-hide" style="margin-left: 23%;">
        <%= render 'tag_search', tag_value: 'Rent', select_value: '' %>
      </div>
      
      <div id="tabs-3" class="ui-tabs-hide" style="margin-left: 23%;">
        <%= render 'tag_search', tag_value: 'Sell', select_value: ["Empty Land", "Empty Land"] %>
      </div>
    </div>
  </div><!-- end container -->
</section>

<section class="module no-padding properties featured" style="margin-bottom: -3%; margin-top: 3%; background: white; padding: 15px; margin-top: -1%;">

  <div class="container" style="margin-top: 3%;">
    <div class="module-header">
      <h2 style="color: #566573"> <%= raw(Setting.first.welcome_msg) %> </h2>
      <%= image_tag "images/divider.png" %>
      <p style="color: #566573"> We provide a simple and convenient way for those in search of real estate in Khartoum to connect with property owners and agents. </p>
    </div>
  </div>
</section> <hr>

<section class="module no-padding properties featured" style="margin-top: 5%;">

  <div class="container">
    <div class="module-header">
      <h2 style="color: #566573">Browse our Featured <strong>Properties</strong> For Sale</h2>
      <%= image_tag "images/divider.png" %>
      <p></p>
    </div>
  </div>

  <div class="slider-nav slider-nav-properties-featured-for-sell">
    <span class="slider-prev"><i class="fa fa-angle-left"></i></span>
    <span class="slider-next"><i class="fa fa-angle-right"></i></span>
  </div>
  
  <div class="slider-wrap" style="width: 80%; margin-left: 10%;">
    <div class="slider slider-featured">
    <% @featureds = Property.all.where(isFeatured: 1, tag: "Sell") %>
    <% @featureds.each do |featured| %>
      <div class="property property-hidden-content slide">
        <a href="<%= property_path(featured) %>" class="property-content responsive-property-content" style="width: 90%;" >
          <div class="property-title">
            <h4> <%= featured.title %> </h4>
            <p class="property-address">
              <i class="fa fa-map-marker icon"></i> 
              <%= featured.address %> 
            </p>
          </div>
          <table class="property-details">
            <tr>
              <td><i class="fa fa-bed"></i>  <%= featured.bedrooms %>  Bedrooms</td>
              <td><i class="fa fa-tint"></i>  <%= featured.bath %>  Bathrooms</td>
              <td><i class="fa fa-expand"></i>  <%= featured.area %>  <%= featured.unit %></td>
            </tr>
          </table>
        </a>
        <a href="<%= property_path(featured) %>" class="property-img responsive-property-img" style="width: 90%;">
            <div class="img-fade"></div>
            <div class="property-tag button alt featured">Featured</div>
            <div class="property-tag button status">
              For Sale
            </div>
            <div class="property-price"> <%= number_with_delimiter(featured.price, delimiter: ',') %> <%= featured.currency %></div>
            <div class="property-color-bar"></div>
            <%= image_tag featured.image.url, style: "height: 210px; width: 100%;" %>
        </a>
      </div>
    <% end %>
    </div><!-- end slider -->
  </div><!-- end slider wrap -->
</section>

<section class="module no-padding properties featured" style="margin-top: 5%; margin-bottom: 10%;">

  <div class="container">
    <div class="module-header">
      <h2 style="color: #566573">Browse our Featured <strong>Properties</strong> For Rent</h2>
      <%= image_tag "images/divider.png" %>
      <p></p>
    </div>
  </div>

  <div class="slider-nav slider-nav-properties-featured-for-rent">
    <span class="slider-prev"><i class="fa fa-angle-left"></i></span>
    <span class="slider-next"><i class="fa fa-angle-right"></i></span>
  </div>
  
  <div class="slider-wrap responsive-slider-wrap" style="margin-top: 4%;width: 80%; margin-left: 10%;">
    <div class="slider slider-featured2">
    <% @featureds = Property.all.where(isFeatured: 1, tag: "Rent") %>
    <% @featureds.each do |featured| %>
      <div class="property property-hidden-content slide">
        <a href="<%= property_path(featured) %>" class="property-content responsive-property-content" style="width: 90%;">
          <div class="property-title">
            <h4> <%= featured.title %> </h4>
            <p class="property-address"><i class="fa fa-map-marker icon"></i> <%= featured.address %> </p>
          </div>
          <table class="property-details">
            <tr>
              <td><i class="fa fa-bed"></i>  <%= featured.bedrooms %>  Bedrooms</td>
              <td><i class="fa fa-tint"></i>  <%= featured.bath %>  Bathrooms</td>
              <td><i class="fa fa-expand"></i>  <%= featured.area %> <%= featured.unit %></td>
            </tr>
          </table>
        </a>
        <a href="<%= property_path(featured) %>" class="property-img responsive-property-img" style="width: 90%;">
            <div class="img-fade"></div>
            <div class="property-tag button alt featured">Featured</div>
            <div class="property-tag button status">For <%= featured.tag.capitalize %></div>
            <div class="property-price"> <%= number_with_delimiter(featured.price, delimiter: ',') %> <%= featured.currency %></div>
            <div class="property-color-bar"></div>
            <%= image_tag featured.image.url, style: "height: 210px; width: 100%;" %>
        </a>
      </div>
    <% end %>
    </div><!-- end slider -->
  </div><!-- end slider wrap -->
</section>

<%= render 'newsletter' %>

app/views/pages/my_properties.html.erb
<% if user_signed_in? %>

	<%
		@properties = current_user.properties
	  	@properties = Kaminari.paginate_array(@properties).page(params[:page]).per(5)
	 %>

	<section class="subheader">
	  <div class="container">
	    <h1>My Properties</h1>
	    <div class="breadcrumb right"> <%= link_to "Home", page_path('index') %> <i class="fa fa-angle-right"></i> <a href="#" class="current"> Properties </a> </div>
	    <div class="clear"></div>
	  </div>
	</section>

	<% flash.each do |key,value| %>
		<div class="alert-box success" style="width: 35%; margin-left: 29.5%; margin-top: 2%; margin-bottom: -3%; ">
			<span style="float: left"><i class="fa fa-check icon"></i></span>
			<p id="notice" style="margin-bottom: 0%;"><%= value %></p>
		</div>
	<% end %>

	<section class="module my-properties">
	  <div class="container">
	  
		<div class="row">
			<%= render "sidebar" %>

			<div class="col-lg-9 col-md-9">
			<% if @properties.count > 0 %>
				<table class="my-properties-list">	
				  <tr>
					<th>Image</th>
					<th>Property</th>
					<th>Post Status</th>
					<th>Date Created</th>
					<th>Actions</th>
				  </tr>
				  <% @properties.each do |property| %>
					  <tr>
							<td class="property-img"><a href="<%= property_path(property) %>"><%= image_tag property.image.url %></a></td>
							<td class="property-title">
								<a href="<%= property_path(property) %>"><%= property.title %></a><br/>
								<p class="property-address"><i class="fa fa-map-marker icon"></i><%= property.address %></p>
								<p><strong><%= property.price %> <%= property.currency %> </strong></p>
							</td>
							<td class="property-post-status"><span class="button small alt"> <%= isPublished_status(property.isPublished) %></span></td>
							<td class="property-date"><%= property.created_at.strftime("%m/%d/%Y") %></td>
							<td class="property-actions">
								<% if property.isPublished? %>
									<%= link_to 'Unpublish', Unpublish_property_path(property), class: 'fa fa-eye icon' %>
								<% else %>
									<%= link_to 'Unpublish', Unpublish_property_path(property), class: 'fa fa-eye icon', style: 'pointer-events: none; color: grey' %>
								<% end %>
								<a href="<%= edit_property_path(property) %>"><i class="fa fa-pencil icon"></i>Edit</a>
								<a><i class="fa fa-close icon"></i></a><%= link_to "Delete", property_path(property),  method: :delete, data: {confirm: "You sure?"}, style: "margin-left: -6%;" %>
							</td>	
					  </tr>
				  <% end %>
				  
				</table>
			<% else %>
				<p align="center" style="margin-top: 14%; margin-left: 28%; width: 53%; font-size: x-large; border-bottom: 2px solid #48a0dc; background-color: white; font-style: oblique;">You have not listed any properties yet. </p>
			<% end %>		
				<span><%= paginate @properties, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-small pagination-centered" %></span>
				
				<div class="clear"></div>
				
			</div><!-- end col -->
		</div><!-- end row -->

	  </div><!-- end container -->
	</section>

	<%= render 'newsletter' %>
<% else %>
	<%= controller.redirect_to page_path('index'), notice: "You must be Signed in to View your Properties. " %>
<% end	%> 	

app/views/pages/scams.html.erb
<section class="subheader">
  <div class="container">
    <h1>Avoid Scams</h1>
    <div class="breadcrumb right">Home <i class="fa fa-angle-right"></i> <a href="#" class="current">Avoid Scams</a></div>
    <div class="clear"></div>
  </div>
</section>

<section class="module">
  <div class="container">

    <div class="row">
      <div class="col-lg-8 col-md-8">
        <div id="accordion" class="content">
          <h3>Avoid Scams</h3>
          <div>
            <%= raw(Setting.first.avoid_scams_text) %>
          </div>
          <h3>Here are tips to help you avoid scam </h3>
          <div>
            <%= raw(Setting.first.tips_avoid_scams_text) %>
          </div>
          
        </div>
      </div>
      <div class="col-lg-4 col-md-4">

        <div class="widget widget-sidebar recent-properties">
        <h4><span>Recent Properties</span> <%= image_tag "images/divider-half.png" %></h4>
        <div class="widget-content">
        <% @recents = Property.order(id: :desc).where(:isPublished => 1).first(3) %>
        <% @recents.each do |recent| %> 
        
        <div class="recent-property">
          <div class="row">
          <div class="col-lg-4 col-md-4 col-sm-4"><a href="<%= property_path(recent) %>"><%= image_tag recent.image.url %></a></div>
          <div class="col-lg-8 col-md-8 col-sm-8">
            <h5><a href="<%= property_path(recent) %>"><%= recent.title %></a></h5>
            <p><strong>$<%= recent.price %></strong> Per Month</p>
          </div>
          </div>
        </div>
         
         <% end %>  
        
        </div><!-- end widget content -->
      </div><!-- end widget -->
        
      </div>
    </div><!-- end row -->

  </div>
</section>

<%= render 'newsletter' %>

app/views/pages/sell.html.erb
<section class="subheader" style="background-image: url(<%= Setting.first.sell_top_image.url %>);">
  <div class="container">
    <h1>Are you looking to Sell your Property?</h1>
    <div class="breadcrumb right">Home <i class="fa fa-angle-right"></i> <a href="#" class="current">Sell</a></div>
    <div class="clear"></div>
  </div>
</section>

<section class="module content" style="background: white">
  <div class="container">

    <div class="row">
      <div class="col-lg-12 col-md-12" style="text-align: center">
        <%= image_tag "images/divider.png", alt: "" %>
        <p><strong style="color: #566573 !important"> <h3> Let Us Help You </h3> </strong> </p>
      </div>
    </div>
    
    <div class="row">
      <div class="col-lg-6 col-md-6" style="text-align: center">
        <i class="fa fa-handshake-o sell-page-icons" aria-hidden="true"></i>
        <p style="text-align: center;"> <strong> Are you a real estate agent? </strong> </p>
        <p style="text-align: center;"> We can help grow your business by connecting you with clients within and outside of Sudan. </p>
      </div>
      
      <div class="col-lg-6 col-md-6" style="text-align: center">
        <i class="fa fa-home sell-page-icons" aria-hidden="true"></i>
        <p style="text-align: center;"> <strong> Are you a property owner?  </strong> </p>
        <p style="text-align: center;"> We can help connect you with one of our real estate agents and make your property visible to buyers worldwide. </p>
      </div>
    </div> <hr>
    
    <div class="col-lg-12 col-md-12" style="text-align: center; margin-top: 0%;">
      <%= link_to 'Contact Us Today', page_path('contact'), class: 'btn btn-primary' %>
    </div>

  </div>
</section>

<%= render 'newsletter' %>

app/views/pages/terms.html.erb
<section class="subheader">
  <div class="container">
    <h1>Terms of Service</h1>
    <div class="breadcrumb right">Home <i class="fa fa-angle-right"></i> <a href="#" class="current">Terms & Services</a></div>
    <div class="clear"></div>
  </div>
</section>

<section class="module">
  <div class="container">

    <div class="row">
      <div class="col-lg-8 col-md-8">
        <div id="accordion" class="content">
          <h3>Terms of Service</h3>
          <div>
            <%= raw(Setting.first.terms_of_services_text) %>
          </div>
          <h3>Accuracy of Information</h3>
          <div>
            <%= raw(Setting.first.accuracy_of_info_text) %>
          </div>
          <h3>Membership & Account Registration</h3>
          <div>
            <%= raw(Setting.first.membership_and_account_reg_text) %>
          </div>
          <h3>General Ownership of Content</h3>
          <div>
            <%= raw(Setting.first.general_ownership_of_account_text) %>
          </div>
          <h3>Changes to the Terms of Service</h3>
          <div>
            <%= raw(Setting.first.changes_to_the_terms_of_service_text) %>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4">

        <div class="widget widget-sidebar recent-properties">
        <h4><span>Recent Properties</span> <%= image_tag "images/divider-half.png" %></h4>
        <div class="widget-content">
        <% @recents = Property.order(id: :desc).where(:isPublished => 1).first(3) %>
        <% @recents.each do |recent| %> 
        
        <div class="recent-property">
          <div class="row">
          <div class="col-lg-4 col-md-4 col-sm-4"><a href="<%= property_path(recent) %>"><%= image_tag recent.image.url %></a></div>
          <div class="col-lg-8 col-md-8 col-sm-8">
            <h5><a href="<%= property_path(recent) %>"><%= recent.title %></a></h5>
            <p><strong>$<%= recent.price %></strong> Per Month</p>
          </div>
          </div>
        </div>
         
         <% end %>  
        
        </div><!-- end widget content -->
      </div><!-- end widget -->
        
      </div>
    </div><!-- end row -->

  </div>
</section>

<%= render 'newsletter' %>