config/routes.rb
Rails.application.routes.draw do
  get 'blogs/index'

  get 'blogs/show'

  mount Ckeditor::Engine => '/ckeditor'
  resources :favorites, only: ['index']

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {confirmations: 'confirmations'}

  resources :properties do
    resources :images, only: [:new, :create]
    
    member do
      get 'mark_favorite'
    end

    collection do 
      get 'search'
    end

    collection do
      post :search, to: 'properties#index'
    end
    
    collection do 
      get 'neighbour_hood_locations'
    end
    
    collection do
      get 'tag_search'
    end
    
    collection do
      post 'contact_form'
    end
    
    collection do
      post 'newsletter'
    end
    
    collection do 
      get 'rent'
    end
    
    collection do 
      get 'buy'
    end

    member do
      get 'Unpublish'
    end
  end
  
  resources :blogs, only: [:index, :show]

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  HighVoltage.configure do |config|
  	config.route_drawer = HighVoltage::RouteDrawers::Root
  end

  HighVoltage.configure do |config|
  	config.home_page = 'index'	
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # before_filter :set_locale
  before_filter :set_search_param
  before_filter :set_cookie

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end

  # def set_locale
  #   I18n.locale = params[:locale] if params[:locale].present?  
  # end

  # def default_url_options(options = {})
  #   {locale: I18n.locale}
  # end 
    
  protected

	  def configure_permitted_parameters
	  	devise_parameter_sanitizer.permit(:sign_up){|u| u.permit(:first_name, :middle_name, :family_name, :email, :password, :password_confirmation, :image, :contact, :terms, :whats_app)}
	  	devise_parameter_sanitizer.permit(:sign_in){|u| u.permit(:email, :password, :remember_me)}
	  	devise_parameter_sanitizer.permit(:account_update){|u| u.permit(:first_name, :middle_name, :family_name, :email, :password, :remember_me, :image, :contact, :whats_app, :current_password)}
	  end
    
    def set_cookie
      cookies[:googtrans] = {
       :value => '',
       :expires => 1.year.from_now
     }
    end
    
    def set_search_param
      @search = Property.ransack(params[:q])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def isPublished_status(status) 
		if status == 1
			return "Published"
		else
			return "Pending"
		end		
	end

	def isFeatured_status(status) 
		if status == 1
			return "Featured"
		else
			return "Not Featured"
		end		
	end
  
  def human_boolean(boolean)
    boolean ? 'Yes' : 'No'
  end

end

app/views/application/_navbar.html.erb
<header data-bind="component: { name: 'main-header', params: $data }, visible: (!isPortrait() || showingModals() <= 0) &amp;&amp; headerVisible">

<a href="<%= page_path('index') %>"> <%= image_tag 'images/high-res-logo.png', class: "logo responsive_logo", 'data-bind' => "click: logoClick", style: 'margin-left: 1%;' %> </a>
<!-- ko component: { name: 'hamburger-menu',  params: $root } --><div class="hamburger" onClick="hamburgerToggle()"></div>
<div class="mobileMenu" data-bind="visible: mobileMenu() &amp;&amp; $root.isPortrait()" style="display: none;" id="mobile_menu">
    <ul>
      <li><a href="<%= rent_properties_path %>" data-bind="text: $data.name, click: $parent.menuClick">Rent</a></li>
      
      <li><a href="<%= buy_properties_path %>" data-bind="text: $data.name, click: $parent.menuClick">Buy</a></li>
      
      <li><a href="<%= page_path('sell') %>" data-bind="text: $data.name, click: $parent.menuClick">Sell</a></li>
      <li><a href="<%= blogs_path %>" data-bind="text: $data.name, click: $parent.menuClick">Blog</a></li>
       
      <li><a href="<%= page_path('about') %>" data-bind="text: $data.name, click: $parent.menuClick">Our Story</a></li>
      <li><a href="<%= page_path('contact') %>">Contact Us</a></li>
      <% if user_signed_in? %>
        <li><a href="<%= edit_user_registration_path %>">Profile</a></li>
      <% end %>
      <li><a href="<%= new_property_path %>">Submit New Property</a></li>
      <li class="translation1"> 
        <div id="google_translate_element"></div>
        <script type="text/javascript">
          function googleTranslateElementInit() {
            new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL, multilanguagePage: true}, 'google_translate_element');
          }
        </script>
      </li>
    </ul>
    
</div>
<ul id="mainMenu" style="margin-left: -1%;">
    <li> <a href="<%= rent_properties_path %>">Rent</a> </li>
    <li> <a href="<%= buy_properties_path %>">Buy</a> </li>
    <li> <a href="<%= page_path('sell') %>">Sell</a> </li>
    <li> <a href="<%= blogs_path %>">Blog</a> </li>
   
    <li><a href="<%= page_path('about') %>">Our Story</a></li>
    <li><a href="<%= page_path('contact') %>">Contact Us</a></li>
    <% if user_signed_in? %>
      <li><a href="<%= edit_user_registration_path %>">Profile</a></li>
    <% end %>
    <li class="translation2" style="width: 28%; margin-top: 1%;"> 
      <div id="google_translate_element"></div>
      <script type="text/javascript">
        function googleTranslateElementInit() {
          new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL, multilanguagePage: true}, 'google_translate_element');
        }
      </script>
      <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
    </li>
</ul>
<div id="secondaryMenu">
  <div class="phone"> <a href="tel:+2001234565665"> <%= Setting.first.phone %> </a> </div>
  <div class="phone"> <a style="background: green; padding: 10px; color: white; border-radius: 4px; text-decoration: none" href="<%= new_property_path %>"><strong> + </strong> List Property</a> </div>
  <div class="sessionInfo">
    <% if user_signed_in? %>
      <button class="dark"><i class="fa fa-sign-in icon"></i><%= link_to "Logout", destroy_user_session_path, class: 'top-bar-item' %> </a></button>
    <% else %>
      <button class="dark"><%= link_to "Login", new_user_session_path %> / <%= link_to "Sign up", new_user_registration_path %> </button>
    <% end %>
  </div>
</div>
<div class="clearfix"></div>

</header>

<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function(event) { 
    $( document ).ready(function() {
      if ($(window).width() < 481){
        $('.translation2').remove();
        $('.translation1').css('display', 'inline');
      }
      else{
        $('.translation1').remove();
        $('.translation2').css('display', '-webkit-inline-box');
      }
    });
  });
</script>

app/views/application/_newsletter.html.erb
<section class="module cta newsletter" style="background-color: #59aee9">
  <div class="container">
  <div class="row">
    <div class="col-lg-1 col-md-1"></div>
    <div class="col-lg-5 col-md-5">
      <h3 style="margin-top: 4%;">Subscribe to our <strong>NewsLetter</strong></h3>
    </div>
    <div class="col-lg-5 col-md-5">
      <form method="post" class="newsletter-form" action="<%= newsletter_properties_path %>" data-remote="true">
        <input name="utf8" type="hidden" value="✓">
        <input type="hidden" name="authenticity_token" value="RQp9E4jYyyPsbaOJmbvvftjumw76y75YFrSmPSD+IOj6K27EhFIOp2qsTJq9dKvE+6PkbULhO6SeyjagUjuUCQ==">
        <input type="email" placeholder="Enter Your Email" name="email" />
        <button type="submit"><i class="fa fa-send"></i></button>
      </form>
      <p style="color: darkslateblue; font-family: fantasy; font-size: larger;" id="newsletter_p"> </p>
    </div>
    <div class="col-lg-1 col-md-1"></div>
  </div><!-- end row -->
  </div><!-- end container -->
</section>

app/views/application/_sidebar.html.erb
<div class="col-lg-3 col-md-3 sidebar-left">
  <div class="widget member-card">
	<div class="member-card-header">
	  <a href="#" class="member-card-avatar"> <%= image_tag current_user.image.url, style: "height: 83px;" %> </a>
	  <h3>
	  	<%= current_user.first_name.capitalize + ' ' + current_user.middle_name.capitalize %>
	  </h3>
	  <p><i class="fa fa-envelope icon"></i><%= current_user.email %></p>
	</div>
	<div class="member-card-content">
	  <ul>
	    <li class="active"><a href="<%= edit_user_registration_path %>"><i class="fa fa-user icon"></i>Profile</a></li>
	    <li><a href="<%= page_path('my_properties') %>"><i class="fa fa-home icon"></i>My Properties</a></li>
	    <li><a href="<%= favorites_path %>"><i class="fa fa-heart icon"></i>Favorited Properties</a></li>
	    <li><a href="<%= edit_user_path %>"><i class="fa fa-key icon" style="font-size: large;"></i>Update Password</a></li>
	    <li><a href="<%= new_property_path %>"><i class="fa fa-plus icon"></i>Submit Property</a></li>
	    <li><i class="fa fa-reply icon" style="float: left; margin-left: 8%; margin-top: 7%;"></i> <%= link_to "Logout", destroy_user_session_path, method: :delete, style: "font-family: inherit;" %> </li>
	  </ul>
	</div>
  </div>
</div>

app/views/application/_tag_search.html.erb
<%= search_form_for @search, url: tag_search_properties_path do |f| %>
  <div style="width: 30%; margin-left: 22%; padding-bottom: 20px" class="widget-content box tag_search"> 
    <div class="form-block border">
      <%= f.select :location_eq, options_for_select([["Khartoum", "Khartoum"], ["Bahri/Khartoum North", "Bahri/Khartoum North"], ["Omdurman", "Omdurman"]]), { prompt: "Select Location" }, { class: 'border' } %>
      
      <%= f.select :listing_type_eq, options_for_select([["Apartment", "Apartment"], ["House", "House"], ["Villa", "Villa"], ["Office", "Office"], ["Farm", "Farm"], select_value]), { prompt: "Select Listing Type" }, { class: "border" } %>
    </div>
    
    <div class="form-block">
      <%= f.number_field :bedrooms_gteq, class: "area-filter border", placeholder: "Min Bedrooms", min: 0 %>
      <%= f.number_field :bedrooms_lteq, class: "area-filter border", placeholder: "Max Bedrooms", min: 0 %>
      <div class="clear"></div>
    </div>

    <div class="form-block border">
      <%= f.select :currency_eq, options_for_select([["USD", "USD"], ["SDG", "SDG"]]), { prompt: "Select Price in USD or SDG" }, { class: 'border' } %>
      <div class="clear"></div>
    </div>

    <div class="form-block">
      <%= f.number_field :price_gteq, class: "area-filter border", placeholder: "Min Price", min: 0 %>
      <%= f.number_field :price_lteq, class: "area-filter border", placeholder: "Max Price", min: 0 %>
      <div class="clear"></div>
    </div>
    
    <div class="form-block">
      <%= f.number_field :bath_gteq, class: "area-filter border", placeholder: "Min Bathrooms", min: 0 %>
      <%= f.number_field :bath_lteq, class: "area-filter border", placeholder: "Max Bathrooms", min: 0 %>
      <div class="clear"></div>
    </div>
    
    <div class="form-block border">
      <%= f.select :furnished_eq, [['Yes', true], ['No', false]], { include_blank: 'Furnished' }, { class: "border  " } %>
      <div class="clear"></div>
    </div>
    
    <%= f.hidden_field :tag_eq, value: tag_value %>
    
    <div class="form-block" align="center">
      <input type="submit" class="button" value="Find Properties" />
    </div>
  </div>
<% end %>